stages:
  - test
  - docker
  - post-docker
  - tag

variables:
  DAST_WEBSITE: https://app.beta.mapotempo.com
  DAST_AUTH_URL: https://app.beta.mapotempo.com/users/sign_in
  DAST_USERNAME: ${DAST_USERNAME}
  DAST_PASSWORD: ${DAST_PASSWORD}
  DAST_USERNAME_FIELD: user[email]
  DAST_PASSWORD_FIELD: user[password]
  REGISTRY_URL: registry.mapotempo.com

include:
  - local: ci-utils/Rails-Tests.gitlab-ci.yml
  - local: ci-utils/Code-Quality.gitlab-ci.yml
  - local: ci-utils/DAST.gitlab-ci.yml
  - local: ci-utils/Container-Scanning.gitlab-ci.yml
  - local: ci-utils/Dependency-Scanning.gitlab-ci.yml
  - local: ci-utils/SAST.gitlab-ci.yml

Build & push Image:
  image: docker:latest
  stage: docker
  cache:
    key: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}
    paths:
      - vendor/bundle
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
  script:
    - apk update > /dev/null && apk add git bash jq curl > /dev/null
    - docker login -u $USER -p $PASSWORD $REGISTRY_URL
    - |
      DOCKER_FILE='./docker/Dockerfile' \
        CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} \
        PORTUS_TOKEN=${PORTUS_TOKEN} \
        PROJECT_NAME=${CI_PROJECT_NAME} \
        REGISTRY_URL=${REGISTRY_URL} \
        TEST_GITHUB=1 \
        USER=$USER \
        ./ci-utils/build_and_push.sh
  only:
    - beta
    - prod
    - master

Tag and close:
  image: debian:latest
  stage: tag
  script:
    - apt-get update -q > /dev/null && apt-get install jq curl git -yqq > /dev/null
    - CI_PROJECT_ID=${CI_PROJECT_ID} MILESTONE=${MILESTONE} PRIVATE_TOKEN=${PRIVATE_TOKEN} LABEL=${CI_COMMIT_REF_NAME} ./ci-utils/tag_and_close.sh
  environment:
    name: ${CI_COMMIT_REF_NAME}
  only:
    - beta
