default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] || ENV['PG_USERNAME'] || 'mapotempo' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || ENV['PG_PASSWORD'] || 'mapotempo' %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'mapotempo-dev' %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'mapotempo-test' %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'mapotempo-prod' %>
